version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: /var/www/booking-system-frontend
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          type: shell
          name: Setup parallelism
          command: |
            circleci tests glob "/var/www/booking-system-frontend/e2e-tests/features/validation_profile_registration.feature" | circleci tests split > /var/www/booking-system-frontend/test_features_for_split_container.txt
            cat /var/www/booking-system-frontend/test_features_for_split_container.txt
      - run:
          name: Login to Docker with Curve account
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS  #just use your docker hub username and password
      - run:
          name: Build application Docker image
          command: |
            docker build -t auslan/api:latest .
      - run:
          name: Running the Docker container and starting server and end to end test
          command: |
            docker run --rm -v /tmp:/usr/src/test-results/ auslan/api /bin/bash -l "./setup_ci.sh"
#      - deploy:
#          name: Deploy to AWS Canary
#          command: |
#            docker run --rm -v /tmp/dist:/usr/src/tmp/dist auslan/api /bin/bash -l "./deploy-to-aws.sh"
##            aws s3 sync /tmp/dist/  s3://auslan-booking-system-ct/ --delete
      - store_artifacts:
          path: /tmp/