version: 2
jobs:
  build:
    docker:
      - image: curvetomorrow/auslan-dev-image:v7.6-debug
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /var/www/booking-system-frontend
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          type: shell
          name: Setup parallelism
          command: |
            circleci tests glob "/var/www/booking-system-frontend/e2e-tests/features/validation_profile_registration.feature" | circleci tests split > /var/www/booking-system-frontend/test_features_for_split_container.txt
            cat /var/www/booking-system-frontend/test_features_for_split_container.txt
      - run:
          name: Running the server and end to end test
          working_directory: /usr/src/app/booking-system-frontend
          environment:
            E2E_ENV: "localhost"
          shell: /bin/bash
          command: |
            bash -l ./setup_ci.sh
      - store_artifacts:
          path: /var/www/booking-system-frontend/.tmp/json-output


#          version: 2
#          jobs:
#            build:
#              docker:
#                - image: curvetomorrow/auslan-dev-image:v7.6-debug
#                  auth:
#                    username: $DOCKER_USER
#                    password: $DOCKER_PASS
#              working_directory: /usr/src/app/booking-system-frontend
#              steps:
#                - checkout
#                - setup_remote_docker:
#                    reusable: true    # default - false
#                - run:
#                    name: Running the server and end to end test
#                    working_directory: /usr/src/app/booking-system-frontend
#                    environment:
#                      E2E_ENV: "localhost"
#                    shell: /bin/bash
#                    command: |
#                      bash -l ./setup_ci.sh
#                - deploy:
#                    name: Deploy Master to AWS S3 Canary
#                    command: |
#                      echo "TODO"