version: 2
jobs:
  build:
    docker:
      - image: curvetomorrow/auslan-dev-image:v7.8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /var/www/booking-system-frontend
    parallelism: 9
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - add_ssh_keys:
          fingerprints:
            - "4f:b6:43:43:0c:10:10:50:3d:30:ce:36:b1:b3:f9:d8"
            - "3a:1b:f4:57:85:e7:ce:3e:85:63:4c:b2:6b:6b:ca:eb"
            - "9f:a5:4b:07:3c:a0:38:17:90:93:4b:5a:52:8e:55:94"
      - run:
          type: shell
          name: Setup parallelism
          command: |
            if [ $CIRCLE_BRANCH = 'master' ];
            then
              circleci tests glob "/var/www/booking-system-frontend/e2e-tests/features/*.feature" | circleci tests split > /var/www/booking-system-frontend/test_features_for_split_container.txt
              cat /var/www/booking-system-frontend/test_features_for_split_container.txt
            fi
            if [ $CIRCLE_BRANCH != 'master' ];
              then
                PR=$(git rev-parse --abbrev-ref HEAD)
                FEATUREFILES=$(git diff --name-only origin/$PR `git merge-base origin/$PR origin/master` | grep feature)
                echo $PR
                echo $FEATUREFILES
                circleci tests glob $FEATUREFILES | circleci tests split > /var/www/booking-system-frontend/test_features_for_split_container.txt
                cat /var/www/booking-system-frontend/test_features_for_split_container.txt
            fi
      - run:
          name: NPM Install
          environment:
            E2E_ENV: "localhost"
          shell: /bin/bash -l
          command: |
            npm install
      - run:
          name: Running the unit tests
          environment:
            E2E_ENV: "localhost"
          shell: /bin/bash -l
          command: |
            if [ "${CIRCLE_NODE_INDEX}" == "0" ]; then
              npm install codeclimate-test-reporter -g
              ./run-unit-test.sh
            fi
      - run:
          name: Setup the server and run E2E tests
          environment:
            E2E_ENV: "localhost"
          shell: /bin/bash -l
          command: |
            ./setup_ci.sh
            ./run-e2e-test.sh
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rm -rf dist
              npm install enhanced-resolve@3.3.0
              ng build --aot --env=canary
              aws s3 sync dist/  s3://auslan-booking-system-ct/ --delete
            else
              echo "Not master branch so not deploying"
            fi
      - store_test_results:
          path: /var/www/booking-system-frontend/.tmp/cucumber
      - store_artifacts:
          path: /var/www/booking-system-api/rails_server.log
      - store_artifacts:
          path: /var/www/booking-system-frontend/.tmp/