version: 2
jobs:
  build:
    docker:
      - image: curvetomorrow/auslan-dev-image:v7.8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /var/www/booking-system-frontend
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "4f:b6:43:43:0c:10:10:50:3d:30:ce:36:b1:b3:f9:d8"
            - "3a:1b:f4:57:85:e7:ce:3e:85:63:4c:b2:6b:6b:ca:eb"
            - "9f:a5:4b:07:3c:a0:38:17:90:93:4b:5a:52:8e:55:94"
      - run:
          type: shell
          name: Setup parallelism
          command: |
            circleci tests glob "/var/www/booking-system-frontend/e2e-tests/features/validation_profile_registration.feature" | circleci tests split > /var/www/booking-system-frontend/test_features_for_split_container.txt
            cat /var/www/booking-system-frontend/test_features_for_split_container.txt
      - run:
          name: Running the server and end to end test
          working_directory: /usr/src/app/booking-system-frontend
          environment:
            E2E_ENV: "localhost"
          shell: /bin/bash -l
          command: |
            /var/www/booking-system-frontend/setup_ci.sh
      - store_artifacts:
          path: /var/www/booking-system-frontend/.tmp/json-output